# Generated by Django 4.0 on 2021-12-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypelist',
            options={'verbose_name_plural': 'Тип продукта Продукта ПодКатегории'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screw.producttypelist', verbose_name='Тип продукта'),
        ),
    ]
