# Generated by Django 4.0 on 2021-12-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screw', '0003_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type_list',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='screw.category', verbose_name='Категория товара'),
            preserve_default=False,
        ),
    ]
